# Compose file for development environment
version: '3.9'

services:
  api:
    image: ghcr.io/cloud-native-engineering/myurlapi:latest
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URI=postgresql://postgres:postgres@db:5432/postgres
      - JWT_ISSUER_URL=https://XX.auth0.com/
      - JWT_AUDIENCE=https://localhost:5005
      - JWKS_URI = https://XX.eu.auth0.com/.well-known/jwks.json
      - SQS_QUEUE_URL = https://<some-queue-url>

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
