# Compose file for development environment
version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Containerfile.dev
    ports:
      - "5005:5000"
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
